# EMIPredict AI - Intelligent Financial Risk Assessment Platform

## Data Exploration

In [5]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [7]:
df = pd.read_csv('emi_prediction_dataset.csv')
df.head(3)

,age,gender,marital_status,education,monthly_salary,employment_type,years_of_employment,company_type,house_type,monthly_rent,...,existing_loans,current_emi_amount,credit_score,bank_balance,emergency_fund,emi_scenario,requested_amount,requested_tenure,emi_eligibility,max_monthly_emi
0,38.0,Female,Married,Professional,82600.0,Private,0.9,Mid-size,Rented,20000.0,...,Yes,23700.0,660.0,303200.0,70200.0,Personal Loan EMI,850000.0,15,Not_Eligible,500.0
1,38.0,Female,Married,Graduate,21500.0,Private,7.0,MNC,Family,0.0,...,Yes,4100.0,714.0,92500.0,26900.0,E-commerce Shopping EMI,128000.0,19,Not_Eligible,700.0
2,38.0,Male,Married,Professional,86100.0,Private,5.8,Startup,Own,0.0,...,No,0.0,650.0,672100.0,324200.0,Education EMI,306000.0,16,Eligible,27775.0

In [9]:
print('Number of Instance: ', df.shape[0])
print('Number of Attributes: ', df.shape[1])

Number of Instance:  404800
Number of Attributes:  27

In [25]:
pd.DataFrame(df.nunique(), columns=['Number of Unique values'])

                        Number of Unique values
age                                          41
gender                                        8
marital_status                                2
education                                     4
monthly_salary                            13662
employment_type                               3
years_of_employment                         356
company_type                                  5
house_type                                    3
monthly_rent                               4396
family_size                                   5
dependents                                    5
school_fees                                 132
college_fees                                202
travel_expenses                             284
groceries_utilities                         544
other_monthly_expenses                      373
existing_loans                                2
current_emi_amount                          508
credit_score                                427
bank_balance                              12261
emergency_fund                             5486
emi_scenario                                  5
requested_amount                           1491
requested_tenure                             82
emi_eligibility                               3
max_monthly_emi                           15383

In [30]:
df.describe()

,years_of_employment,monthly_rent,family_size,dependents,school_fees,college_fees,travel_expenses,groceries_utilities,other_monthly_expenses,current_emi_amount,credit_score,emergency_fund,requested_amount,requested_tenure,max_monthly_emi
count,404800.000000,402374.000000,404800.000000,404800.000000,404800.000000,404800.000000,404800.000000,404800.000000,404800.000000,404800.000000,402380.000000,402449.000000,4.048000e+05,404800.000000,404800.000000
mean,5.364079,5828.446490,2.940425,1.940425,4624.575593,4066.253706,5687.497777,12804.999506,7119.309783,4543.407609,700.856223,96769.051731,3.708554e+05,29.126677,6763.602156
std,6.079135,8648.604639,1.075199,1.075199,5061.074401,7319.344289,3392.671132,6993.853745,4510.447300,7034.901139,88.435548,81373.053976,3.451945e+05,18.100854,7741.263317
min,0.500000,0.000000,1.000000,0.000000,0.000000,0.000000,600.000000,1800.000000,600.000000,0.000000,0.000000,1400.000000,1.000000e+04,3.000000,500.000000
25%,1.200000,0.000000,2.000000,1.000000,0.000000,0.000000,3200.000000,7700.000000,3800.000000,0.000000,654.000000,38400.000000,1.240000e+05,15.000000,500.000000
50%,3.200000,0.000000,3.000000,2.000000,3000.000000,0.000000,4900.000000,11400.000000,6000.000000,0.000000,701.000000,74000.000000,2.360000e+05,25.000000,4211.200000
75%,7.200000,10600.000000,4.000000,3.000000,9000.000000,6500.000000,7400.000000,16400.000000,9300.000000,8000.000000,748.000000,130600.000000,4.940000e+05,40.000000,9792.000000
max,36.000000,80000.000000,5.000000,4.000000,15000.000000,25000.000000,30300.000000,71200.000000,42900.000000,56300.000000,1200.000000,891500.000000,1.500000e+06,84.000000,91040.400000

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 404800 entries, 0 to 404799
Data columns (total 27 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   age                     404800 non-null  object
 1   gender                  404800 non-null  object
 2   marital_status          404800 non-null  object
 3   education               402396 non-null  object
 4   monthly_salary          404800 non-null  object
 5   employment_type         404800 non-null  object
 6   years_of_employment     404800 non-null  float64
 7   company_type            404800 non-null  object
 8   house_type              404800 non-null  object
 9   monthly_rent            402374 non-null  float64
 10  family_size             404800 non-null  int64
 11  dependents              404800 non-null  int64
 12  school_fees             404800 non-null  float64
 13  college_fees            404800 non-null  float64
 14  travel_expenses         404800 non-null  float64
 15  groceries_utilities     404800 non-null  float64
 16  other_monthly_expenses  404800 non-null  float64
 17  existing_loans          404800 non-null  object
 18  current_emi_amount      404800 non-null  float64
 19  credit_score            402380 non-null  float64
 20  bank_balance            402374 non-null  object
 21  emergency_fund          402449 non-null  float64
 22  emi_scenario            404800 non-null  object
 23  requested_amount        404800 non-null  float64
 24  requested_tenure        404800 non-null  int64
 25  emi_eligibility         404800 non-null  object
 26  max_monthly_emi         404800 non-null  float64
dtypes: float64(12), int64(3), object(12)
memory usage: 83.4+ MB

In [29]:
pd.DataFrame(df.isna().sum(), columns=['Total number of Null values'])

                        Total number of Null values
age                                               0
gender                                            0
marital_status                                    0
education                                      2404
monthly_salary                                    0
employment_type                                   0
years_of_employment                               0
company_type                                      0
house_type                                        0
monthly_rent                                   2426
family_size                                       0
dependents                                        0
school_fees                                       0
college_fees                                      0
travel_expenses                                   0
groceries_utilities                               0
other_monthly_expenses                            0
existing_loans                                    0
current_emi_amount                                0
credit_score                                   2420
bank_balance                                   2426
emergency_fund                                 2351
emi_scenario                                      0
requested_amount                                  0
requested_tenure                                  0
emi_eligibility                                   0
max_monthly_emi                                   0